version: "3.9"

services:
  home-client:
    build: .
    container_name: home-client
    restart: unless-stopped
    environment:
      TV_IP: "${TV_IP}"
      TV_PSK: "${TV_PSK}"
      NETFLIX_URI: "com.sony.dtv.com.netflix.ninja.com.netflix.ninja.MainActivity"
      DISNEY_URI: "com.sony.dtv.com.disney.disneyplus.com.bamtechmedia.dominguez.main.MainActivity"
      YOUTUBE_URI: "com.sony.dtv.com.google.android.youtube.tv.com.google.android.apps.youtube.tv.activity.ShellActivity"
      DAZN_URI: "com.sony.dtv.com.dazn.com.dazn.MainActivity"
      TV_URI: "com.sony.dtv.com.sony.dtv.tvx.com.sony.dtv.tvx.MainActivity"
    ports:
      - "8087:8080"
    networks:
      - home_client_net

networks:
  home_client_net:
    driver: bridge
